name: stern_plot
channels:
  - conda-forge
dependencies:
  - python=3.13
  # Dataframes
  - pandas
  # Plotting
  - plotly=5
  - python-kaleido=0.1.0
  # Utilities
  - ruff
  - pillow # For reading logo image
  # Notebook
  - jupyter
  - nbformat
  # Other
  - pip
  - pip:
    - -e .

# To install: conda env create -f environment.yml
# To update: conda env update -f environment.yml --prune -n SternPlot